{% set name = "aubio" %}
{% set version = "0.4.7" %}
{% set sha256 = "cbed4afec5ab3a1a6300c7e3af0a1369379aa94259f5e701a8ca905cdd9fa041" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://aubio.org/pub/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - pkg-config  # [not win]
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - numpy
    - ffmpeg        # [not (win and py27)]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - ffmpeg        # [not (win and py27)]

test:
  imports:
    - aubio

about:
  home: https://aubio.org
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'tools for audio and music analysis and transformation'
  description: |
    aubio provides a set of tools for analysis and transformation of sounds.
    Numpy arrays are used to store vectors and matrices, while computations
    are done in C, for speed and memory efficiency.
  doc_url: https://aubio.org/manual/latest
  dev_url: https://github.com/aubio/aubio/

extra:
  recipe-maintainers:
    - piem
    - MartinHN
