{% set name = "aubio" %}
{% set version = "0.4.6" %}
{% set sha256 = "bdc73be1f007218d3ea6d2a503b38a217815a0e2ccc4ed441f6e850ed5d47cfb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://aubio.org/pub/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - avcodec_declfirst.patch  # [win and py27]

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - numpy 1.11.*
    - pkg-config  # [not win]
    - msinttypes  # [win and py27]
    - ffmpeg 2.8.*
  run:
    - python
    - numpy >=1.11
    - ffmpeg 2.8.*

test:
  imports:
    - aubio

about:
  home: https://aubio.org
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'tools for audio and music analysis and transformation'
  description: |
    aubio provides a set of tools for analysis and transformation of sounds.
    Numpy arrays are used to store vectors and matrices, while computations
    are done in C, for speed and memory efficiency.
  doc_url: https://aubio.org/manual/latest
  dev_url: https://github.com/aubio/aubio/

extra:
  recipe-maintainers:
    - piem
    - MartinHN
