travis:
  secure:
    BINSTAR_TOKEN: De6oShszvJYwY9xrwp4EYU/+ds2vk8h/DDGdxWW5vDStUdye4OTvOaNR1pA8MAyNaOs3q7Bru7oKEIRDE8PnSZcVYLDqqoKOKMJ7XD1yEUDZ7/Epyn1UD5ZSZq1eR07SkFsbajP/Fx1WlW/02F7R0nMx6Gc+qCz+eDUpe/sBs3O0Se05+xBkt6dx5B/LcNvHM+7XI64EjIjEogXFm7mKMVjt79ee45334DRkiF2rbgXie7itnqjwlbV5KuskPGDlERKp9MbqhRTCpzbmoGnAlVV6lIedxTbu7pIgBrFlTIwh2LKxvgYwVumyN9D/4bS7SV6EtCu2UevAQZapigpq0toaJNIQFFAXzRVcEQB1ZXCo0YkkElZeBhp3nGXsO4ktqOIeQuUefPeTEPdE90UppXIubg0MyeLYqI10UgQP54EoZtCbTD9nOxx46e2DgVgFxnOaNna6geEJ1CvCpbUYuK0dKVSKyCW5fY5eHe5rnmKV/YP4LA44+EQAHK0DM35xGC1OFwPEDTUwGCTGnIHnX+fYI3d96j2hhTpaPCPhAOBy2+EXwDXOPWGbwT3JHyQaS/NZ0foJh7jo4nHAZITknGqpB+lbjh43iepK+aKYOYdqBvJTiueCZfpMW/koFJ16SeFIqNB3NMRiDsMtZwionWSEdO3Gy1yf+lYwV/WEv/o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
